apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkoutio-ui-container
  description: Checkout UI container for the VTEX Store Framework - provides the loading structure and UI components for the Checkout IO experience
  annotations:
    github.com/project-slug: vtex-apps/checkout
    vtex.com/o11y-os-index: ''
    vtex.com/janus-acronym: ''
    grafana/dashboard-selector: ''
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: T3ZFAMZO
  tags:
    - typescript
spec:
  type: backend-api
  lifecycle: experimental
  owner: te-0001
  system: checkout
  dependsOn: []
